#Depending on the operating system of the host machines(s) that will build or run the containers, the image specified in the FROM statement may need to be changed.
#For more information, please see https://aka.ms/containercompat

FROM mcr.microsoft.com/dotnet/core/aspnet:2.1-nanoserver-1903 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/core/sdk:2.1-nanoserver-1903 AS build
WORKDIR /src
COPY ["APIs/APIs.csproj", "APIs/"]
COPY ["Services/Services.csproj", "Services/"]
COPY ["Domains/Domains.csproj", "Domains/"]
COPY ["Utilities/Utilities.csproj", "Utilities/"]
RUN dotnet restore "APIs/APIs.csproj"
COPY . .
WORKDIR "/src/APIs"
RUN dotnet build "APIs.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "APIs.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "APIs.dll"]